[workspace]
resolver = "2"
exclude = ["packages/vendor/iocraft"]
members = [
    "packages/cli",
    "packages/agent",
    "packages/lifecycle",
    "packages/daemon",
    "packages/worker",
    "packages/commands",
    "packages/llms",
    "packages/config",
    "packages/tools",
    "packages/tui",
]

[profile.release]
lto = true

[patch.crates-io]
iocraft = { path = "packages/vendor/iocraft" }
