use spectacular_agent::{AgentEvent, TiktokenTokenCounter, TokenCounter};
use spectacular_llms::{ProviderMessageRole, UsageMetadata};

/// Tracks total model tokens for the current assistant turn.
#[derive(Default)]
pub(super) struct AssistantTurnTokenCounter {
    estimator: TurnTokenEstimator,
    approximated_content: String,
    provider_input_tokens: Option<u64>,
    provider_output_tokens: Option<u64>,
    provider_total_tokens: Option<u64>,
}

impl AssistantTurnTokenCounter {
    /// Creates a turn token counter using a model-aware local estimator when available.
    pub(super) fn for_model(model: &str) -> Self {
        Self {
            estimator: TurnTokenEstimator::for_model(model),
            ..Self::default()
        }
    }

    /// Adds visible assistant delta content to the approximate current token count.
    pub(super) fn add_visible_delta(&mut self, content: &str) {
        self.add_approximate_content(content);
    }

    /// Adds visible reasoning delta content to the approximate current token count.
    pub(super) fn add_reasoning_delta(&mut self, content: &str) {
        self.add_approximate_content(content);
    }

    /// Adds a tool-call request payload generated by the assistant to the token count.
    pub(super) fn add_tool_call(&mut self, name: &str, arguments: &str) {
        self.add_approximate_content(name);
        self.add_approximate_content(arguments);
    }

    /// Updates the current turn token count from provider-reported usage when available.
    pub(super) fn reconcile_usage(&mut self, usage: &UsageMetadata) {
        if let Some(input_tokens) = usage.input_tokens {
            self.provider_input_tokens = Some(input_tokens);
        }
        if let Some(output_tokens) = usage.output_tokens {
            self.provider_output_tokens = Some(output_tokens);
        }
        if let Some(total_tokens) = usage.total_tokens {
            self.provider_total_tokens = Some(total_tokens);
        }
    }

    /// Returns the best current assistant-turn token count for spinner rendering.
    pub(super) fn current_tokens(&self) -> Option<u64> {
        self.provider_total_tokens
            .or_else(|| {
                provider_input_plus_output(self.provider_input_tokens, self.provider_output_tokens)
            })
            .or_else(|| self.estimator.count_text_tokens(&self.approximated_content))
    }

    /// Adds non-empty generated content to the local approximation buffer.
    fn add_approximate_content(&mut self, content: &str) {
        if content.is_empty() {
            return;
        }

        self.approximated_content.push_str(content);
    }
}

/// Local estimator for pre-provider turn token counts.
#[derive(Clone, Copy)]
enum TurnTokenEstimator {
    Tiktoken(TiktokenTokenCounter),
    Approximate,
}

impl TurnTokenEstimator {
    /// Creates a model-aware tiktoken estimator with approximate fallback.
    fn for_model(model: &str) -> Self {
        TiktokenTokenCounter::for_model(model)
            .map(TurnTokenEstimator::Tiktoken)
            .unwrap_or(TurnTokenEstimator::Approximate)
    }

    /// Counts generated text tokens for interim working-line display.
    fn count_text_tokens(&self, content: &str) -> Option<u64> {
        if content.is_empty() {
            return None;
        }

        match self {
            TurnTokenEstimator::Tiktoken(counter) => {
                Some(counter.count_text_tokens(content) as u64)
            }
            TurnTokenEstimator::Approximate => Some(approximate_tokens(content)),
        }
    }
}

impl Default for TurnTokenEstimator {
    /// Creates the fallback estimator used when no runtime model is available.
    fn default() -> Self {
        TurnTokenEstimator::Approximate
    }
}

/// Adds any generated-token-bearing event to the current turn token estimate.
pub(super) fn record_generated_tokens(event: &AgentEvent, counter: &mut AssistantTurnTokenCounter) {
    match event {
        AgentEvent::MessageDelta(delta)
            if is_visible_assistant_delta(delta.role, &delta.content) =>
        {
            counter.add_visible_delta(&delta.content);
        }
        AgentEvent::ReasoningDelta(delta) if !delta.content.trim().is_empty() => {
            counter.add_reasoning_delta(&delta.content);
        }
        AgentEvent::AssistantToolCallRequest {
            name, arguments, ..
        } => counter.add_tool_call(name, arguments),
        AgentEvent::UsageMetadata(usage) => counter.reconcile_usage(usage),
        _ => {}
    }
}

/// Returns true for streamed assistant deltas that should count toward turn tokens.
pub(super) fn is_visible_assistant_delta(role: ProviderMessageRole, content: &str) -> bool {
    role == ProviderMessageRole::Assistant && !content.trim().is_empty()
}

/// Adds provider input and output tokens when both sides of the turn are known.
fn provider_input_plus_output(
    input_tokens: Option<u64>,
    output_tokens: Option<u64>,
) -> Option<u64> {
    Some(input_tokens?.saturating_add(output_tokens?))
}

/// Applies the repository fallback token heuristic to visible text.
fn approximate_tokens(content: &str) -> u64 {
    content.chars().count().div_ceil(4) as u64
}
